import request from '@/utils/request'

/**
 * 获取院系、系别信息，若想查询所有的院系 类型id为 1，要是想查询某个学院下的系，typeid=null(不填)，parentid等于学院id
 * @param {*} typeId 类型id   
 * @param {*} parentValue 父类id    
 */
export const getCollegeInfo = (typeId, parentValue) => {
  return request({
    baseURL: 'http://140.143.201.244:8081/HBO/sys/comm/',
    method: 'GET',
    url: '/getselectes',
    params: {
      typeId,
      parentValue
    }
  })
}


/**
 * 获取社团的所有权限信息
 */
export const getPremits = () => {
  // return request({
  //   url: '',
  //   method: 'GET',
  //   params: {

  //   }
  // })
  return new Promise((resolve) => {
    let data = {
      code: 0,
      msg: '',
      page: {
        totalCount: 4
      },
      organize: [{
          "menuId": 1,
          "parentId": 0,
          "parentName": null,
          "name": "organize",
          "url": "/organize",
          "perms": null,
          "type": 0,
          "icon": "organize",
          "orderNum": 0,
          "open": null,
          "list": null,
          "hidden": null,
          "title": "组织管理",
          "redirect": "/organize/user",
          "alwaysShow": null,
          "useCache": null,
          "query": null
        },
        {
          "menuId": 2,
          "parentId": 1,
          "parentName": "organize",
          "name": "user",
          "url": "user",
          "perms": null,
          "type": 1,
          "icon": "",
          "orderNum": 1,
          "open": null,
          "list": null,
          "hidden": null,
          "title": "社团成员",
          "redirect": null,
          "alwaysShow": null,
          "useCache": null,
          "query": null
        },
        {
          "menuId": 6,
          "parentId": 2,
          "parentName": "user",
          "name": "add-user",
          "url": "",
          "perms": null,
          "type": 2,
          "icon": "",
          "orderNum": 1,
          "open": null,
          "list": null,
          "hidden": null,
          "title": "添加成员",
          "redirect": null,
          "alwaysShow": null,
          "useCache": null,
          "query": null
        },
        {
          "menuId": 7,
          "parentId": 2,
          "parentName": "user",
          "name": "edit-user-info",
          "url": "",
          "perms": null,
          "type": 2,
          "icon": "",
          "orderNum": 1,
          "open": null,
          "list": null,
          "hidden": null,
          "title": "修改成员",
          "redirect": null,
          "alwaysShow": null,
          "useCache": null,
          "query": null
        },
        {
          "menuId": 8,
          "parentId": 2,
          "parentName": "user",
          "name": "delete-user",
          "url": "",
          "perms": null,
          "type": 2,
          "icon": "",
          "orderNum": 1,
          "open": null,
          "list": null,
          "hidden": null,
          "title": "删除成员",
          "redirect": null,
          "alwaysShow": null,
          "useCache": null,
          "query": null
        },
        {
          "menuId": 3,
          "parentId": 1,
          "parentName": "organize",
          "name": "depart",
          "url": "depart",
          "perms": null,
          "type": 1,
          "icon": "",
          "orderNum": 2,
          "open": null,
          "list": null,
          "hidden": null,
          "title": "部门管理",
          "redirect": null,
          "alwaysShow": null,
          "useCache": null,
          "query": null
        },
        {
          "menuId": 9,
          "parentId": 3,
          "parentName": "depart",
          "name": "add-depart",
          "url": "",
          "perms": null,
          "type": 2,
          "icon": "",
          "orderNum": 1,
          "open": null,
          "list": null,
          "hidden": null,
          "title": "添加部门",
          "redirect": null,
          "alwaysShow": null,
          "useCache": null,
          "query": null
        },
        {
          "menuId": 11,
          "parentId": 3,
          "parentName": "depart",
          "name": "delete-depart",
          "url": "",
          "perms": null,
          "type": 2,
          "icon": "",
          "orderNum": 1,
          "open": null,
          "list": null,
          "hidden": null,
          "title": "删除部门",
          "redirect": null,
          "alwaysShow": null,
          "useCache": null,
          "query": null
        },
        {
          "menuId": 10,
          "parentId": 3,
          "parentName": "depart",
          "name": "edit-depart",
          "url": "",
          "perms": null,
          "type": 2,
          "icon": "",
          "orderNum": 1,
          "open": null,
          "list": null,
          "hidden": null,
          "title": "修改部门",
          "redirect": null,
          "alwaysShow": null,
          "useCache": null,
          "query": null
        },
        {
          "menuId": 5,
          "parentId": 1,
          "parentName": "organize",
          "name": "role",
          "url": "role",
          "perms": null,
          "type": 1,
          "icon": "",
          "orderNum": 4,
          "open": null,
          "list": null,
          "hidden": null,
          "title": "角色管理",
          "redirect": null,
          "alwaysShow": null,
          "useCache": null,
          "query": null
        },
      ],
      recruited: [ {
          alwaysShow: null,
          hidden: null,
          icon: "recruited",
          list: null,
          menuId: 57,
          name: "recruited",
          open: null,
          orderNum: null,
          parentId: 0,
          parentName: null,
          perms: null,
          query: null,
          redirect: "/recruited/resume",
          title: "纳新管理",
          type: 0,
          url: "/recruited",
          useCache: null,
        },
        {
          alwaysShow: null,
          hidden: null,
          icon: null,
          list: null,
          menuId: 59,
          name: "resume-list",
          open: null,
          orderNum: null,
          parentId: 57,
          parentName: null,
          perms: null,
          query: null,
          redirect: null,
          title: "纳新信息",
          type: 1,
          url: "resume",
          useCache: null,
        },
        {
          alwaysShow: null,
          hidden: null,
          icon: null,
          list: null,
          menuId: 60,
          name: "edit-resume",
          open: null,
          orderNum: null,
          parentId: 59,
          parentName: null,
          perms: null,
          query: null,
          redirect: null,
          title: "修改简历",
          type: 2,
          url: "",
          useCache: null,
        },
        {
          alwaysShow: null,
          hidden: null,
          icon: null,
          list: null,
          menuId: 61,
          name: "delete-resume",
          open: null,
          orderNum: null,
          parentId: 59,
          parentName: null,
          perms: null,
          query: null,
          redirect: null,
          title: "删除简历",
          type: 2,
          url: "",
          useCache: null,
        }
      ]
    }
    setTimeout(() => {
      resolve(data)
    }, 1000)
  })
}